//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using System.Globalization;
using System.Resources;

namespace Baketa.UI.Resources;

/// <summary>
/// A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
public static class Strings
{
    private static ResourceManager? _resourceMan;
    private static CultureInfo? _resourceCulture;

    /// <summary>
    /// Returns the cached ResourceManager instance used by this class.
    /// </summary>
    public static ResourceManager ResourceManager
    {
        get
        {
            if (_resourceMan is null)
            {
                _resourceMan = new ResourceManager("Baketa.UI.Resources.Strings", typeof(Strings).Assembly);
            }
            return _resourceMan;
        }
    }

    /// <summary>
    /// Overrides the current thread's CurrentUICulture property for all
    /// resource lookups using this strongly typed resource class.
    /// </summary>
    public static CultureInfo? Culture
    {
        get => _resourceCulture;
        set => _resourceCulture = value;
    }

    /// <summary>
    /// Gets the localized string for the specified key.
    /// </summary>
    public static string GetString(string name)
    {
        return ResourceManager.GetString(name, _resourceCulture) ?? name;
    }

    /// <summary>
    /// Gets the localized string for the specified key with format arguments.
    /// </summary>
    public static string GetString(string name, params object[] args)
    {
        var value = ResourceManager.GetString(name, _resourceCulture) ?? name;
        return string.Format(CultureInfo.CurrentCulture, value, args);
    }

    // ========== App General ==========

    /// <summary>
    /// Looks up a localized string similar to 'Baketa'.
    /// </summary>
    public static string App_Title => GetString("App_Title");

    /// <summary>
    /// Looks up a localized string similar to 'Loading...'.
    /// </summary>
    public static string App_LoadingMessage => GetString("App_LoadingMessage");

    /// <summary>
    /// Looks up a localized string similar to 'Error'.
    /// </summary>
    public static string App_ErrorTitle => GetString("App_ErrorTitle");

    /// <summary>
    /// Looks up a localized string similar to 'Current Version: {0}'.
    /// </summary>
    public static string App_Version => GetString("App_Version");

    /// <summary>
    /// Looks up a localized string.
    /// </summary>
    public static string App_Copyright => GetString("App_Copyright");

    // ========== Common Buttons ==========

    public static string Common_Save => GetString("Common_Save");
    public static string Common_Cancel => GetString("Common_Cancel");
    public static string Common_Apply => GetString("Common_Apply");
    public static string Common_Reset => GetString("Common_Reset");
    public static string Common_Close => GetString("Common_Close");
    public static string Common_OK => GetString("Common_OK");
    public static string Common_Yes => GetString("Common_Yes");
    public static string Common_No => GetString("Common_No");
    public static string Common_Help => GetString("Common_Help");
    public static string Common_Loading => GetString("Common_Loading");
    public static string Common_Or => GetString("Common_Or");
    public static string Common_Submit => GetString("Common_Submit");

    // ========== Main Overlay ==========

    public static string MainOverlay_Minimize => GetString("MainOverlay_Minimize");
    public static string MainOverlay_SelectWindow => GetString("MainOverlay_SelectWindow");
    public static string MainOverlay_Target => GetString("MainOverlay_Target");
    public static string MainOverlay_ShowHideTranslation => GetString("MainOverlay_ShowHideTranslation");
    public static string MainOverlay_LiveTranslation => GetString("MainOverlay_LiveTranslation");
    public static string MainOverlay_ShotTranslation => GetString("MainOverlay_ShotTranslation");
    public static string MainOverlay_Preparing => GetString("MainOverlay_Preparing");
    public static string MainOverlay_ShowTranslation => GetString("MainOverlay_ShowTranslation");
    public static string MainOverlay_Settings => GetString("MainOverlay_Settings");
    public static string MainOverlay_Exit => GetString("MainOverlay_Exit");
    public static string MainOverlay_Expand => GetString("MainOverlay_Expand");
    public static string MainOverlay_SelectedWindow => GetString("MainOverlay_SelectedWindow");
    public static string MainOverlay_TranslationCount => GetString("MainOverlay_TranslationCount");

    // ========== Home View ==========

    public static string Home_QuickStart => GetString("Home_QuickStart");
    public static string Home_StartCapture => GetString("Home_StartCapture");
    public static string Home_CaptureSettings => GetString("Home_CaptureSettings");
    public static string Home_TranslationSettings => GetString("Home_TranslationSettings");
    public static string Home_RecentTranslations => GetString("Home_RecentTranslations");
    public static string Home_ViewAll => GetString("Home_ViewAll");
    public static string Home_NoHistory => GetString("Home_NoHistory");
    public static string Home_UsageStatistics => GetString("Home_UsageStatistics");
    public static string Home_CaptureStatus => GetString("Home_CaptureStatus");
    public static string Home_TranslationEngine => GetString("Home_TranslationEngine");
    public static string Home_TargetLanguage => GetString("Home_TargetLanguage");
    public static string Home_MemoryUsage => GetString("Home_MemoryUsage");
    public static string Home_RunningTime => GetString("Home_RunningTime");
    public static string Home_Tips => GetString("Home_Tips");
    public static string Home_Tip_OpenTabs => GetString("Home_Tip_OpenTabs");
    public static string Home_Tip_SelectArea => GetString("Home_Tip_SelectArea");
    public static string Home_Tip_OverlaySettings => GetString("Home_Tip_OverlaySettings");
    public static string Home_Tip_TranslationHistory => GetString("Home_Tip_TranslationHistory");

    // ========== Settings Window ==========

    public static string Settings_Title => GetString("Settings_Title");

    // ========== General Settings ==========

    public static string Settings_General_Title => GetString("Settings_General_Title");
    public static string Settings_General_Subtitle => GetString("Settings_General_Subtitle");
    public static string Settings_General_Appearance => GetString("Settings_General_Appearance");
    public static string Settings_General_Theme => GetString("Settings_General_Theme");
    public static string Settings_General_ThemeDescription => GetString("Settings_General_ThemeDescription");
    public static string Settings_General_ThemeLight => GetString("Settings_General_ThemeLight");
    public static string Settings_General_ThemeDark => GetString("Settings_General_ThemeDark");
    public static string Settings_General_ThemeAuto => GetString("Settings_General_ThemeAuto");
    public static string Settings_General_Translation => GetString("Settings_General_Translation");
    public static string Settings_General_TranslationEngine => GetString("Settings_General_TranslationEngine");
    public static string Settings_General_TranslationEngineDescription => GetString("Settings_General_TranslationEngineDescription");
    public static string Settings_General_OfflineTranslation => GetString("Settings_General_OfflineTranslation");
    public static string Settings_General_AITranslation => GetString("Settings_General_AITranslation");
    public static string Settings_General_AlphaNote => GetString("Settings_General_AlphaNote");
    public static string Settings_General_CloudTranslationUpgradeNote => GetString("Settings_General_CloudTranslationUpgradeNote");
    public static string Settings_General_TranslationLanguage => GetString("Settings_General_TranslationLanguage");
    public static string Settings_General_TranslationLanguageDescription => GetString("Settings_General_TranslationLanguageDescription");
    public static string Settings_General_FontSize => GetString("Settings_General_FontSize");
    public static string Settings_General_FontSizeDescription => GetString("Settings_General_FontSizeDescription");
    public static string Settings_General_FontSizeUnit => GetString("Settings_General_FontSizeUnit");
    public static string Settings_General_LanguagePairWarning => GetString("Settings_General_LanguagePairWarning");
    public static string Settings_General_Language => GetString("Settings_General_Language");
    public static string Settings_General_LanguageDescription => GetString("Settings_General_LanguageDescription");
    public static string Settings_General_LanguageJapanese => GetString("Settings_General_LanguageJapanese");
    public static string Settings_General_LanguageEnglish => GetString("Settings_General_LanguageEnglish");

    // ========== Translation Settings ==========

    public static string Settings_Translation_Title => GetString("Settings_Translation_Title");
    public static string Settings_Translation_Subtitle => GetString("Settings_Translation_Subtitle");
    public static string Settings_Translation_LastSaved => GetString("Settings_Translation_LastSaved");
    public static string Settings_Translation_UnsavedChanges => GetString("Settings_Translation_UnsavedChanges");
    public static string Settings_Translation_DiscardChanges => GetString("Settings_Translation_DiscardChanges");
    public static string Settings_Translation_Summary => GetString("Settings_Translation_Summary");
    public static string Settings_Translation_Engine => GetString("Settings_Translation_Engine");
    public static string Settings_Translation_LanguagePair => GetString("Settings_Translation_LanguagePair");
    public static string Settings_Translation_Strategy => GetString("Settings_Translation_Strategy");
    public static string Settings_Translation_ChineseVariant => GetString("Settings_Translation_ChineseVariant");
    public static string Settings_Translation_Fallback => GetString("Settings_Translation_Fallback");
    public static string Settings_Translation_ChangeStatus => GetString("Settings_Translation_ChangeStatus");
    public static string Settings_Translation_Import => GetString("Settings_Translation_Import");
    public static string Settings_Translation_ImportTip => GetString("Settings_Translation_ImportTip");
    public static string Settings_Translation_Export => GetString("Settings_Translation_Export");
    public static string Settings_Translation_ExportTip => GetString("Settings_Translation_ExportTip");
    public static string Settings_Translation_Load => GetString("Settings_Translation_Load");
    public static string Settings_Translation_LoadTip => GetString("Settings_Translation_LoadTip");
    public static string Settings_Translation_SaveTip => GetString("Settings_Translation_SaveTip");
    public static string Settings_Translation_ApplyTip => GetString("Settings_Translation_ApplyTip");
    public static string Settings_Translation_Saving => GetString("Settings_Translation_Saving");

    // ========== Capture Settings ==========

    public static string Settings_Capture_Title => GetString("Settings_Capture_Title");
    public static string Settings_Capture_Subtitle => GetString("Settings_Capture_Subtitle");
    public static string Settings_Capture_Basic => GetString("Settings_Capture_Basic");
    public static string Settings_Capture_Enabled => GetString("Settings_Capture_Enabled");
    public static string Settings_Capture_EnabledDescription => GetString("Settings_Capture_EnabledDescription");
    public static string Settings_Capture_Interval => GetString("Settings_Capture_Interval");
    public static string Settings_Capture_IntervalDescription => GetString("Settings_Capture_IntervalDescription");
    public static string Settings_Capture_Quality => GetString("Settings_Capture_Quality");
    public static string Settings_Capture_QualityDescription => GetString("Settings_Capture_QualityDescription");
    public static string Settings_Capture_AreaMode => GetString("Settings_Capture_AreaMode");
    public static string Settings_Capture_AreaModeDescription => GetString("Settings_Capture_AreaModeDescription");
    public static string Settings_Capture_AutoDetect => GetString("Settings_Capture_AutoDetect");
    public static string Settings_Capture_FixedArea => GetString("Settings_Capture_FixedArea");
    public static string Settings_Capture_FixedAreaSection => GetString("Settings_Capture_FixedAreaSection");
    public static string Settings_Capture_Position => GetString("Settings_Capture_Position");
    public static string Settings_Capture_PositionDescription => GetString("Settings_Capture_PositionDescription");
    public static string Settings_Capture_Advanced => GetString("Settings_Capture_Advanced");
    public static string Settings_Capture_Monitor => GetString("Settings_Capture_Monitor");
    public static string Settings_Capture_MonitorDescription => GetString("Settings_Capture_MonitorDescription");
    public static string Settings_Capture_DpiScaling => GetString("Settings_Capture_DpiScaling");
    public static string Settings_Capture_DpiScalingDescription => GetString("Settings_Capture_DpiScalingDescription");
    public static string Settings_Capture_HardwareAccel => GetString("Settings_Capture_HardwareAccel");
    public static string Settings_Capture_HardwareAccelDescription => GetString("Settings_Capture_HardwareAccelDescription");
    public static string Settings_Capture_DiffDetection => GetString("Settings_Capture_DiffDetection");
    public static string Settings_Capture_DiffDetectionEnable => GetString("Settings_Capture_DiffDetectionEnable");
    public static string Settings_Capture_DiffDetectionDescription => GetString("Settings_Capture_DiffDetectionDescription");

    // ========== OCR Settings ==========

    public static string Settings_OCR_Title => GetString("Settings_OCR_Title");
    public static string Settings_OCR_Subtitle => GetString("Settings_OCR_Subtitle");
    public static string Settings_OCR_Basic => GetString("Settings_OCR_Basic");
    public static string Settings_OCR_Enabled => GetString("Settings_OCR_Enabled");
    public static string Settings_OCR_EnabledDescription => GetString("Settings_OCR_EnabledDescription");
    public static string Settings_OCR_Language => GetString("Settings_OCR_Language");
    public static string Settings_OCR_LanguageDescription => GetString("Settings_OCR_LanguageDescription");
    public static string Settings_OCR_TargetLanguage => GetString("Settings_OCR_TargetLanguage");
    public static string Settings_OCR_TargetLanguageDescription => GetString("Settings_OCR_TargetLanguageDescription");
    public static string Settings_OCR_Confidence => GetString("Settings_OCR_Confidence");
    public static string Settings_OCR_ConfidenceDescription => GetString("Settings_OCR_ConfidenceDescription");
    public static string Settings_OCR_Filtering => GetString("Settings_OCR_Filtering");
    public static string Settings_OCR_FilteringDescription => GetString("Settings_OCR_FilteringDescription");
    public static string Settings_OCR_Advanced => GetString("Settings_OCR_Advanced");
    public static string Settings_OCR_Preprocessing => GetString("Settings_OCR_Preprocessing");
    public static string Settings_OCR_PreprocessingEnable => GetString("Settings_OCR_PreprocessingEnable");
    public static string Settings_OCR_PreprocessingDescription => GetString("Settings_OCR_PreprocessingDescription");
    public static string Settings_OCR_Grayscale => GetString("Settings_OCR_Grayscale");

    // ========== Overlay Settings ==========

    public static string Settings_Overlay_Title => GetString("Settings_Overlay_Title");
    public static string Settings_Overlay_Subtitle => GetString("Settings_Overlay_Subtitle");
    public static string Settings_Overlay_ARNote => GetString("Settings_Overlay_ARNote");
    public static string Settings_Overlay_Basic => GetString("Settings_Overlay_Basic");
    public static string Settings_Overlay_Enabled => GetString("Settings_Overlay_Enabled");
    public static string Settings_Overlay_EnabledDescription => GetString("Settings_Overlay_EnabledDescription");
    public static string Settings_Overlay_Opacity => GetString("Settings_Overlay_Opacity");
    public static string Settings_Overlay_OpacityDescription => GetString("Settings_Overlay_OpacityDescription");
    public static string Settings_Overlay_FontSize => GetString("Settings_Overlay_FontSize");
    public static string Settings_Overlay_FontSizeDescription => GetString("Settings_Overlay_FontSizeDescription");
    public static string Settings_Overlay_BackgroundColor => GetString("Settings_Overlay_BackgroundColor");
    public static string Settings_Overlay_BackgroundColorDescription => GetString("Settings_Overlay_BackgroundColorDescription");
    public static string Settings_Overlay_ChooseColor => GetString("Settings_Overlay_ChooseColor");
    public static string Settings_Overlay_TextColor => GetString("Settings_Overlay_TextColor");
    public static string Settings_Overlay_TextColorDescription => GetString("Settings_Overlay_TextColorDescription");
    public static string Settings_Overlay_AutoHide => GetString("Settings_Overlay_AutoHide");
    public static string Settings_Overlay_AutoHideAuto => GetString("Settings_Overlay_AutoHideAuto");
    public static string Settings_Overlay_AutoHideAutoDescription => GetString("Settings_Overlay_AutoHideAutoDescription");
    public static string Settings_Overlay_AutoHideAutoDelay => GetString("Settings_Overlay_AutoHideAutoDelay");
    public static string Settings_Overlay_AutoHideAutoDelayDescription => GetString("Settings_Overlay_AutoHideAutoDelayDescription");
    public static string Settings_Overlay_AutoHideShotDelay => GetString("Settings_Overlay_AutoHideShotDelay");
    public static string Settings_Overlay_AutoHideShotDelayDescription => GetString("Settings_Overlay_AutoHideShotDelayDescription");
    public static string Settings_Overlay_ManualClose => GetString("Settings_Overlay_ManualClose");
    public static string Settings_Overlay_ManualCloseDescription => GetString("Settings_Overlay_ManualCloseDescription");

    // ========== Account Settings ==========

    public static string Settings_Account_Title => GetString("Settings_Account_Title");
    public static string Settings_Account_Subtitle => GetString("Settings_Account_Subtitle");
    public static string Settings_Account_Processing => GetString("Settings_Account_Processing");
    public static string Settings_Account_LoggedInWith => GetString("Settings_Account_LoggedInWith");
    public static string Settings_Account_LoggedInStatus => GetString("Settings_Account_LoggedInStatus");
    public static string Settings_Account_Actions => GetString("Settings_Account_Actions");
    public static string Settings_Account_LogoutDescription => GetString("Settings_Account_LogoutDescription");
    public static string Settings_Account_NotLoggedIn => GetString("Settings_Account_NotLoggedIn");
    public static string Settings_Account_LoginBenefits => GetString("Settings_Account_LoginBenefits");
    public static string Settings_Account_ForgotPassword => GetString("Settings_Account_ForgotPassword");
    public static string Settings_Account_PasswordReset => GetString("Settings_Account_PasswordReset");
    public static string Settings_Account_PasswordResetDescription => GetString("Settings_Account_PasswordResetDescription");
    public static string Settings_Account_ResetEmailSent => GetString("Settings_Account_ResetEmailSent");
    public static string Settings_Account_EmailAddress => GetString("Settings_Account_EmailAddress");
    public static string Settings_Account_Profile => GetString("Settings_Account_Profile");
    public static string Settings_Account_Email => GetString("Settings_Account_Email");
    public static string Settings_Account_ChangePassword => GetString("Settings_Account_ChangePassword");
    public static string Settings_Account_Logout => GetString("Settings_Account_Logout");
    public static string Settings_Account_Login => GetString("Settings_Account_Login");
    public static string Settings_Account_Signup => GetString("Settings_Account_Signup");
    public static string Settings_Account_CurrentPlan => GetString("Settings_Account_CurrentPlan");
    public static string Settings_Account_UpgradeToPremium => GetString("Settings_Account_UpgradeToPremium");

    // ========== Account Settings - Patreon ==========

    public static string Settings_Account_PatreonSection => GetString("Settings_Account_PatreonSection");
    public static string Settings_Account_PatreonUserFallback => GetString("Settings_Account_PatreonUserFallback");
    public static string Settings_Account_PatreonPlanLabel => GetString("Settings_Account_PatreonPlanLabel");
    public static string Settings_Account_PatreonLastSync => GetString("Settings_Account_PatreonLastSync");
    public static string Settings_Account_PatreonSyncNow => GetString("Settings_Account_PatreonSyncNow");
    public static string Settings_Account_PatreonDisconnect => GetString("Settings_Account_PatreonDisconnect");
    public static string Settings_Account_PatreonConnectTitle => GetString("Settings_Account_PatreonConnectTitle");
    public static string Settings_Account_PatreonConnectDescription => GetString("Settings_Account_PatreonConnectDescription");
    public static string Settings_Account_PatreonConnectButton => GetString("Settings_Account_PatreonConnectButton");
    public static string Settings_Account_PatreonAvailablePlans => GetString("Settings_Account_PatreonAvailablePlans");
    public static string Settings_Account_PatreonPlanStandard => GetString("Settings_Account_PatreonPlanStandard");
    public static string Settings_Account_PatreonPlanPro => GetString("Settings_Account_PatreonPlanPro");
    public static string Settings_Account_PatreonPlanPremia => GetString("Settings_Account_PatreonPlanPremia");
    public static string Settings_Account_EmailLoginOptional => GetString("Settings_Account_EmailLoginOptional");
    public static string Settings_Account_PatreonSyncing => GetString("Settings_Account_PatreonSyncing");
    public static string Settings_Account_PatreonStatusSynced => GetString("Settings_Account_PatreonStatusSynced");
    public static string Settings_Account_PatreonStatusOffline => GetString("Settings_Account_PatreonStatusOffline");
    public static string Settings_Account_PatreonStatusTokenExpired => GetString("Settings_Account_PatreonStatusTokenExpired");
    public static string Settings_Account_PatreonStatusError => GetString("Settings_Account_PatreonStatusError");
    public static string Settings_Account_PatreonStatusNotConnected => GetString("Settings_Account_PatreonStatusNotConnected");
    public static string Settings_Account_PatreonLinkedFormat => GetString("Settings_Account_PatreonLinkedFormat");
    public static string Settings_Account_MockModeTestUser => GetString("Settings_Account_MockModeTestUser");

    // ========== License Settings ==========

    public static string Settings_License_Title => GetString("Settings_License_Title");
    public static string Settings_License_Subtitle => GetString("Settings_License_Subtitle");
    public static string Settings_License_Loading => GetString("Settings_License_Loading");
    public static string Settings_License_TokenUsage => GetString("Settings_License_TokenUsage");
    public static string Settings_License_MonthlyUsage => GetString("Settings_License_MonthlyUsage");
    public static string Settings_License_QuotaExceeded => GetString("Settings_License_QuotaExceeded");
    public static string Settings_License_LocalOnlyMessage => GetString("Settings_License_LocalOnlyMessage");
    public static string Settings_License_PlanDetails => GetString("Settings_License_PlanDetails");
    public static string Settings_License_ExpirationDate => GetString("Settings_License_ExpirationDate");
    public static string Settings_License_CloudAccess => GetString("Settings_License_CloudAccess");
    public static string Settings_License_MonthlyLimit => GetString("Settings_License_MonthlyLimit");
    public static string Settings_License_Refresh => GetString("Settings_License_Refresh");
    public static string License_Plan_Free => GetString("License_Plan_Free");
    public static string License_Plan_Standard => GetString("License_Plan_Standard");
    public static string License_Plan_Pro => GetString("License_Plan_Pro");
    public static string License_Plan_Premia => GetString("License_Plan_Premia");
    public static string License_Plan_Unknown => GetString("License_Plan_Unknown");
    public static string License_Plan_PromotionSuffix => GetString("License_Plan_PromotionSuffix");

    // ========== Promotion Code Section ==========

    public static string Settings_License_PromotionCode => GetString("Settings_License_PromotionCode");
    public static string Settings_License_PromotionExpires => GetString("Settings_License_PromotionExpires");
    public static string Settings_License_PromotionCodeDescription => GetString("Settings_License_PromotionCodeDescription");
    public static string Settings_License_PromotionApply => GetString("Settings_License_PromotionApply");
    public static string Settings_License_PromotionVerifying => GetString("Settings_License_PromotionVerifying");
    public static string Settings_License_PromotionAppliedFormat => GetString("Settings_License_PromotionAppliedFormat");
    public static string Settings_License_PromotionPlanPromo => GetString("Settings_License_PromotionPlanPromo");

    public static string License_Desc_Free => GetString("License_Desc_Free");
    public static string License_Desc_Standard => GetString("License_Desc_Standard");
    public static string License_Desc_Pro => GetString("License_Desc_Pro");
    public static string License_Desc_Premia => GetString("License_Desc_Premia");
    public static string License_NoExpiration => GetString("License_NoExpiration");
    public static string License_LocalOnly => GetString("License_LocalOnly");
    public static string License_RefreshSuccess => GetString("License_RefreshSuccess");
    public static string License_RefreshFailed => GetString("License_RefreshFailed");
    public static string Settings_License_Upgrade => GetString("Settings_License_Upgrade");
    public static string License_UpgradeComingSoon => GetString("License_UpgradeComingSoon");
    public static string License_OpeningPlanPage => GetString("License_OpeningPlanPage");
    public static string License_PlanPageOpenFailed => GetString("License_PlanPageOpenFailed");

    // ========== Advanced Settings ==========

    public static string Settings_Advanced_Title => GetString("Settings_Advanced_Title");
    public static string Settings_Advanced_Subtitle => GetString("Settings_Advanced_Subtitle");
    public static string Settings_Advanced_Warning => GetString("Settings_Advanced_Warning");
    public static string Settings_Advanced_Basic => GetString("Settings_Advanced_Basic");
    public static string Settings_Advanced_CPU => GetString("Settings_Advanced_CPU");
    public static string Settings_Advanced_Memory => GetString("Settings_Advanced_Memory");
    public static string Settings_Advanced_Network => GetString("Settings_Advanced_Network");
    public static string Settings_Advanced_Seconds => GetString("Settings_Advanced_Seconds");
    public static string Settings_Advanced_Connections => GetString("Settings_Advanced_Connections");
    public static string Settings_Advanced_Retry => GetString("Settings_Advanced_Retry");
    public static string Settings_Advanced_Times => GetString("Settings_Advanced_Times");
    public static string Settings_Advanced_Statistics => GetString("Settings_Advanced_Statistics");
    public static string Settings_Advanced_Days => GetString("Settings_Advanced_Days");
    public static string Settings_Advanced_Experimental => GetString("Settings_Advanced_Experimental");
    public static string Settings_Advanced_Danger => GetString("Settings_Advanced_Danger");

    // ========== Login View ==========

    public static string Auth_Login_Title => GetString("Auth_Login_Title");
    public static string Auth_Login_Google => GetString("Auth_Login_Google");
    public static string Auth_Login_Discord => GetString("Auth_Login_Discord");
    public static string Auth_Login_Twitch => GetString("Auth_Login_Twitch");
    public static string Auth_Login_Email => GetString("Auth_Login_Email");
    public static string Auth_Login_EmailPlaceholder => GetString("Auth_Login_EmailPlaceholder");
    public static string Auth_Login_Password => GetString("Auth_Login_Password");
    public static string Auth_Login_PasswordPlaceholder => GetString("Auth_Login_PasswordPlaceholder");
    public static string Auth_Login_RememberMe => GetString("Auth_Login_RememberMe");
    public static string Auth_Login_ForgotPassword => GetString("Auth_Login_ForgotPassword");
    public static string Auth_Login_Button => GetString("Auth_Login_Button");
    public static string Auth_Login_Loading => GetString("Auth_Login_Loading");
    public static string Auth_Login_SignupPrompt => GetString("Auth_Login_SignupPrompt");
    public static string Auth_Login_SignupLink => GetString("Auth_Login_SignupLink");

    // ========== Signup View ==========

    public static string Auth_Signup_Title => GetString("Auth_Signup_Title");
    public static string Auth_Signup_Google => GetString("Auth_Signup_Google");
    public static string Auth_Signup_Discord => GetString("Auth_Signup_Discord");
    public static string Auth_Signup_Twitch => GetString("Auth_Signup_Twitch");
    public static string Auth_Signup_OrEmail => GetString("Auth_Signup_OrEmail");
    public static string Auth_Signup_DisplayName => GetString("Auth_Signup_DisplayName");
    public static string Auth_Signup_DisplayNamePlaceholder => GetString("Auth_Signup_DisplayNamePlaceholder");
    public static string Auth_Signup_Email => GetString("Auth_Signup_Email");
    public static string Auth_Signup_Password => GetString("Auth_Signup_Password");
    public static string Auth_Signup_PasswordPlaceholder => GetString("Auth_Signup_PasswordPlaceholder");
    public static string Auth_Signup_PasswordRequirement => GetString("Auth_Signup_PasswordRequirement");
    public static string Auth_Signup_ConfirmPassword => GetString("Auth_Signup_ConfirmPassword");
    public static string Auth_Signup_ConfirmPasswordPlaceholder => GetString("Auth_Signup_ConfirmPasswordPlaceholder");
    public static string Auth_Signup_Terms => GetString("Auth_Signup_Terms");
    public static string Auth_Signup_TermsAgree => GetString("Auth_Signup_TermsAgree");
    public static string Auth_Signup_Privacy => GetString("Auth_Signup_Privacy");
    public static string Auth_Signup_Button => GetString("Auth_Signup_Button");
    public static string Auth_Signup_Loading => GetString("Auth_Signup_Loading");
    public static string Auth_Signup_LoginPrompt => GetString("Auth_Signup_LoginPrompt");
    public static string Auth_Signup_LoginLink => GetString("Auth_Signup_LoginLink");

    // ========== Premium Plan ==========

    public static string Premium_Title => GetString("Premium_Title");
    public static string Premium_FeatureAdFree => GetString("Premium_FeatureAdFree");
    public static string Premium_FeatureCloudTranslation => GetString("Premium_FeatureCloudTranslation");
    public static string Premium_FeaturePrioritySupport => GetString("Premium_FeaturePrioritySupport");
    public static string Premium_FeatureEarlyAccess => GetString("Premium_FeatureEarlyAccess");
    public static string Premium_Monthly => GetString("Premium_Monthly");
    public static string Premium_Yearly => GetString("Premium_Yearly");

    // ========== Error Messages ==========

    public static string Error_NetworkError => GetString("Error_NetworkError");
    public static string Error_AuthenticationFailed => GetString("Error_AuthenticationFailed");
    public static string Error_TranslationFailed => GetString("Error_TranslationFailed");
    public static string Error_OcrFailed => GetString("Error_OcrFailed");
    public static string Error_WindowNotFound => GetString("Error_WindowNotFound");
    public static string Error_InvalidEmail => GetString("Error_InvalidEmail");
    public static string Error_PasswordTooShort => GetString("Error_PasswordTooShort");
    public static string Error_LoginFailed => GetString("Error_LoginFailed");
    public static string Error_PasswordMismatch => GetString("Error_PasswordMismatch");
    public static string Error_SignupFailed => GetString("Error_SignupFailed");

    // ========== Confirmation Dialogs ==========

    public static string Dialog_LogoutConfirm => GetString("Dialog_LogoutConfirm");
    public static string Dialog_DiscardChanges => GetString("Dialog_DiscardChanges");
    public static string Dialog_ResetSettings => GetString("Dialog_ResetSettings");
    public static string Dialog_ExitApp => GetString("Dialog_ExitApp");

    // ========== MainOverlay Tooltips ==========

    public static string MainOverlay_StartButton_Tooltip => GetString("MainOverlay_StartButton_Tooltip");
    public static string MainOverlay_Singleshot_Execute => GetString("MainOverlay_Singleshot_Execute");
    public static string MainOverlay_Singleshot_Clear => GetString("MainOverlay_Singleshot_Clear");
    public static string MainOverlay_Status_Initializing => GetString("MainOverlay_Status_Initializing");
    public static string MainOverlay_Status_Idle => GetString("MainOverlay_Status_Idle");
    public static string MainOverlay_Status_Ready => GetString("MainOverlay_Status_Ready");
    public static string MainOverlay_Status_Translating => GetString("MainOverlay_Status_Translating");
    public static string MainOverlay_Status_Waiting => GetString("MainOverlay_Status_Waiting");
    public static string MainOverlay_Warmup_Failed => GetString("MainOverlay_Warmup_Failed");
    public static string MainOverlay_Warmup_Loading => GetString("MainOverlay_Warmup_Loading");
    public static string MainOverlay_Warmup_Complete => GetString("MainOverlay_Warmup_Complete");

    // ========== Theme Options ==========

    public static string Theme_Light => GetString("Theme_Light");
    public static string Theme_Dark => GetString("Theme_Dark");
    public static string Theme_Auto => GetString("Theme_Auto");

    // ========== Size Options ==========

    public static string Size_Small => GetString("Size_Small");
    public static string Size_Medium => GetString("Size_Medium");
    public static string Size_Large => GetString("Size_Large");

    // ========== Advanced Settings Toggle ==========

    public static string Settings_Advanced_Show => GetString("Settings_Advanced_Show");
    public static string Settings_Advanced_Hide => GetString("Settings_Advanced_Hide");

    // ========== Settings Window Status Messages ==========

    public static string Settings_Window_Title => GetString("Settings_Window_Title");
    public static string Settings_Status_HasChanges => GetString("Settings_Status_HasChanges");
    public static string Settings_Status_NoChanges => GetString("Settings_Status_NoChanges");
    public static string Settings_Status_Saving => GetString("Settings_Status_Saving");
    public static string Settings_Status_Saved => GetString("Settings_Status_Saved");
    public static string Settings_Status_SaveFailed => GetString("Settings_Status_SaveFailed");
    public static string Settings_Status_AccessDenied => GetString("Settings_Status_AccessDenied");
    public static string Settings_Status_IOError => GetString("Settings_Status_IOError");
    public static string Settings_Status_Cancelled => GetString("Settings_Status_Cancelled");
    public static string Settings_Status_Reset => GetString("Settings_Status_Reset");

    // ========== Settings Window Buttons ==========

    public static string Settings_Button_Reset => GetString("Settings_Button_Reset");
    public static string Settings_Button_Cancel => GetString("Settings_Button_Cancel");
    public static string Settings_Button_Save => GetString("Settings_Button_Save");
    public static string Settings_Tooltip_Reset => GetString("Settings_Tooltip_Reset");
    public static string Settings_Tooltip_Cancel => GetString("Settings_Tooltip_Cancel");
    public static string Settings_Tooltip_Save => GetString("Settings_Tooltip_Save");

    // ========== Loading Screen ==========

    // [Issue #185] Component download step
    public static string Loading_DownloadingComponents => GetString("Loading_DownloadingComponents");
    public static string Loading_ResolvingDependencies => GetString("Loading_ResolvingDependencies");
    public static string Loading_LoadingOCR => GetString("Loading_LoadingOCR");
    public static string Loading_InitializingTranslation => GetString("Loading_InitializingTranslation");
    public static string Loading_PreparingUI => GetString("Loading_PreparingUI");
    public static string Loading_SetupGpu => GetString("Loading_SetupGpu");

    // ========== [Issue #78 Phase 5] Token Usage Alerts ==========

    public static string TokenUsage_Warning_Title => GetString("TokenUsage_Warning_Title");
    public static string TokenUsage_Warning80_Message => GetString("TokenUsage_Warning80_Message");
    public static string TokenUsage_Warning90_Message => GetString("TokenUsage_Warning90_Message");
    public static string TokenUsage_Exceeded_Title => GetString("TokenUsage_Exceeded_Title");
    public static string TokenUsage_Exceeded_Message => GetString("TokenUsage_Exceeded_Message");

    // ========== [Issue #78 Phase 5] Cloud Usage Display ==========

    public static string Settings_General_CloudUsageLabel => GetString("Settings_General_CloudUsageLabel");
    public static string Settings_General_CloudUsageTokens => GetString("Settings_General_CloudUsageTokens");

    // ========== [Issue #249] Update Dialog ==========

    public static string Update_WindowTitle => GetString("Update_WindowTitle");
    public static string Update_HeaderText => GetString("Update_HeaderText");
    public static string Update_InfoText => GetString("Update_InfoText");
    public static string Update_SkipButton => GetString("Update_SkipButton");
    public static string Update_RemindLaterButton => GetString("Update_RemindLaterButton");
    public static string Update_DownloadButton => GetString("Update_DownloadButton");
}
