name: Feature Request
description: Suggest a new feature or improvement for Baketa
title: "[Feature] "
labels: ["type: feature", "priority: low"]
assignees:
  - koizumiiiii

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see.
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're experiencing...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Essential for my use case
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of Baketa does this feature relate to?
      options:
        - Translation - Translation engines or accuracy
        - UI/UX - User interface or experience
        - OCR - Text detection and recognition
        - Performance - Speed or resource usage
        - Settings - Configuration and preferences
        - Integration - External services or APIs
        - Other - Please specify in additional context
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request.
      placeholder: Any additional information, examples, or mockups...