//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baketa.Core.Resources;

using System;
using System.Resources;
using System.Globalization;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Messages
{
    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Messages()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baketa.Core.Resources.Messages", typeof(Messages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
        get
        {
            return resourceCulture;
        }
        set
        {
            resourceCulture = value;
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to プロモーションコードの形式が正しくありません。BAKETA-XXXX-XXXX の形式で入力してください。
    /// </summary>
    public static string Promotion_InvalidFormat
    {
        get
        {
            return ResourceManager.GetString("Promotion_InvalidFormat", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to プロモーションコードが適用されました。
    /// </summary>
    public static string Promotion_Applied
    {
        get
        {
            return ResourceManager.GetString("Promotion_Applied", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to 既にProプラン以上が適用されています。
    /// </summary>
    public static string Promotion_AlreadyProOrHigher
    {
        get
        {
            return ResourceManager.GetString("Promotion_AlreadyProOrHigher", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to サーバーに接続できません。インターネット接続を確認してください。
    /// </summary>
    public static string Promotion_ConnectionError
    {
        get
        {
            return ResourceManager.GetString("Promotion_ConnectionError", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to サーバーからの応答がタイムアウトしました。
    /// </summary>
    public static string Promotion_Timeout
    {
        get
        {
            return ResourceManager.GetString("Promotion_Timeout", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to 予期しないエラーが発生しました。
    /// </summary>
    public static string Promotion_UnexpectedError
    {
        get
        {
            return ResourceManager.GetString("Promotion_UnexpectedError", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to サーバーからの応答形式が不正です
    /// </summary>
    public static string Promotion_InvalidResponseFormat
    {
        get
        {
            return ResourceManager.GetString("Promotion_InvalidResponseFormat", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to サーバーからの応答が大きすぎます
    /// </summary>
    public static string Promotion_ResponseTooLarge
    {
        get
        {
            return ResourceManager.GetString("Promotion_ResponseTooLarge", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to 応答の解析に失敗しました
    /// </summary>
    public static string Promotion_ParseError
    {
        get
        {
            return ResourceManager.GetString("Promotion_ParseError", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to サーバーからの応答にプラン情報がありません
    /// </summary>
    public static string Promotion_NoPlanInfo
    {
        get
        {
            return ResourceManager.GetString("Promotion_NoPlanInfo", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to 不明なエラーが発生しました
    /// </summary>
    public static string Promotion_UnknownError
    {
        get
        {
            return ResourceManager.GetString("Promotion_UnknownError", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to コードの適用に失敗しました。
    /// </summary>
    public static string Promotion_ApplyFailed
    {
        get
        {
            return ResourceManager.GetString("Promotion_ApplyFailed", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to サーバーエラー: {0}
    /// </summary>
    public static string Promotion_ServerError
    {
        get
        {
            return ResourceManager.GetString("Promotion_ServerError", resourceCulture);
        }
    }

    /// <summary>
    ///   Looks up a localized string similar to [モックモード] プロモーションコードが適用されました。
    /// </summary>
    public static string Promotion_MockModeApplied
    {
        get
        {
            return ResourceManager.GetString("Promotion_MockModeApplied", resourceCulture);
        }
    }
}
