# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ocr_pb2 as ocr__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ocr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OcrServiceStub(object):
    """/ Baketa OCRサービス
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/baketa.ocr.v1.OcrService/Recognize',
                request_serializer=ocr__pb2.OcrRequest.SerializeToString,
                response_deserializer=ocr__pb2.OcrResponse.FromString,
                _registered_method=True)
        self.RecognizeBatch = channel.unary_unary(
                '/baketa.ocr.v1.OcrService/RecognizeBatch',
                request_serializer=ocr__pb2.RecognizeBatchRequest.SerializeToString,
                response_deserializer=ocr__pb2.RecognizeBatchResponse.FromString,
                _registered_method=True)
        self.Detect = channel.unary_unary(
                '/baketa.ocr.v1.OcrService/Detect',
                request_serializer=ocr__pb2.DetectRequest.SerializeToString,
                response_deserializer=ocr__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/baketa.ocr.v1.OcrService/HealthCheck',
                request_serializer=ocr__pb2.OcrHealthCheckRequest.SerializeToString,
                response_deserializer=ocr__pb2.OcrHealthCheckResponse.FromString,
                _registered_method=True)
        self.IsReady = channel.unary_unary(
                '/baketa.ocr.v1.OcrService/IsReady',
                request_serializer=ocr__pb2.OcrIsReadyRequest.SerializeToString,
                response_deserializer=ocr__pb2.OcrIsReadyResponse.FromString,
                _registered_method=True)
        self.SwitchDevice = channel.unary_unary(
                '/baketa.ocr.v1.OcrService/SwitchDevice',
                request_serializer=ocr__pb2.SwitchDeviceRequest.SerializeToString,
                response_deserializer=ocr__pb2.SwitchDeviceResponse.FromString,
                _registered_method=True)


class OcrServiceServicer(object):
    """/ Baketa OCRサービス
    """

    def Recognize(self, request, context):
        """/ 画像からテキストを認識（Detection + Recognition）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeBatch(self, request, context):
        """/ [Issue #330] 複数画像の一括認識（Batch Recognition）
        / 部分OCRで複数領域を処理する際のgRPC呼び出しオーバーヘッドを削減
        / Pythonサーバーはmax_workers=1のため、内部的には逐次処理だが
        / gRPC呼び出し回数を15→1に削減することで大幅に高速化
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detect(self, request, context):
        """/ [Issue #320] テキスト領域の位置のみ検出（Detection Only）
        / Recognition（テキスト認識）をスキップし、約10倍高速化
        / ROI学習用の高速検出に使用
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """/ ヘルスチェック
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsReady(self, request, context):
        """/ 準備状態確認
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchDevice(self, request, context):
        """/ [Issue #334] デバイス切り替え（GPU/CPU）
        / VRAM不足時にCPUモードへ自動フォールバックするために使用
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OcrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=ocr__pb2.OcrRequest.FromString,
                    response_serializer=ocr__pb2.OcrResponse.SerializeToString,
            ),
            'RecognizeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeBatch,
                    request_deserializer=ocr__pb2.RecognizeBatchRequest.FromString,
                    response_serializer=ocr__pb2.RecognizeBatchResponse.SerializeToString,
            ),
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=ocr__pb2.DetectRequest.FromString,
                    response_serializer=ocr__pb2.DetectResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ocr__pb2.OcrHealthCheckRequest.FromString,
                    response_serializer=ocr__pb2.OcrHealthCheckResponse.SerializeToString,
            ),
            'IsReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsReady,
                    request_deserializer=ocr__pb2.OcrIsReadyRequest.FromString,
                    response_serializer=ocr__pb2.OcrIsReadyResponse.SerializeToString,
            ),
            'SwitchDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchDevice,
                    request_deserializer=ocr__pb2.SwitchDeviceRequest.FromString,
                    response_serializer=ocr__pb2.SwitchDeviceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'baketa.ocr.v1.OcrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('baketa.ocr.v1.OcrService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OcrService(object):
    """/ Baketa OCRサービス
    """

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baketa.ocr.v1.OcrService/Recognize',
            ocr__pb2.OcrRequest.SerializeToString,
            ocr__pb2.OcrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baketa.ocr.v1.OcrService/RecognizeBatch',
            ocr__pb2.RecognizeBatchRequest.SerializeToString,
            ocr__pb2.RecognizeBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baketa.ocr.v1.OcrService/Detect',
            ocr__pb2.DetectRequest.SerializeToString,
            ocr__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baketa.ocr.v1.OcrService/HealthCheck',
            ocr__pb2.OcrHealthCheckRequest.SerializeToString,
            ocr__pb2.OcrHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baketa.ocr.v1.OcrService/IsReady',
            ocr__pb2.OcrIsReadyRequest.SerializeToString,
            ocr__pb2.OcrIsReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baketa.ocr.v1.OcrService/SwitchDevice',
            ocr__pb2.SwitchDeviceRequest.SerializeToString,
            ocr__pb2.SwitchDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
