# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import translation_pb2 as protos_dot_translation__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/translation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranslationServiceStub(object):
    """============================================================================
    Service Definition
    ============================================================================

    / <summary>
    / Baketa翻訳サービス
    / Phase 2: gRPC通信によるPython翻訳サーバーとの連携
    / </summary>
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Translate = channel.unary_unary(
                '/baketa.translation.v1.TranslationService/Translate',
                request_serializer=protos_dot_translation__pb2.TranslateRequest.SerializeToString,
                response_deserializer=protos_dot_translation__pb2.TranslateResponse.FromString,
                _registered_method=True)
        self.TranslateBatch = channel.unary_unary(
                '/baketa.translation.v1.TranslationService/TranslateBatch',
                request_serializer=protos_dot_translation__pb2.BatchTranslateRequest.SerializeToString,
                response_deserializer=protos_dot_translation__pb2.BatchTranslateResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/baketa.translation.v1.TranslationService/HealthCheck',
                request_serializer=protos_dot_translation__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=protos_dot_translation__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.IsReady = channel.unary_unary(
                '/baketa.translation.v1.TranslationService/IsReady',
                request_serializer=protos_dot_translation__pb2.IsReadyRequest.SerializeToString,
                response_deserializer=protos_dot_translation__pb2.IsReadyResponse.FromString,
                _registered_method=True)


class TranslationServiceServicer(object):
    """============================================================================
    Service Definition
    ============================================================================

    / <summary>
    / Baketa翻訳サービス
    / Phase 2: gRPC通信によるPython翻訳サーバーとの連携
    / </summary>
    """

    def Translate(self, request, context):
        """/ <summary>
        / 単一テキストを翻訳します
        / </summary>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranslateBatch(self, request, context):
        """/ <summary>
        / 複数のテキストをバッチ翻訳します
        / </summary>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """/ <summary>
        / サーバーのヘルスチェックを実行します
        / </summary>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsReady(self, request, context):
        """/ <summary>
        / サーバーが準備完了かどうかを確認します
        / </summary>
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=protos_dot_translation__pb2.TranslateRequest.FromString,
                    response_serializer=protos_dot_translation__pb2.TranslateResponse.SerializeToString,
            ),
            'TranslateBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateBatch,
                    request_deserializer=protos_dot_translation__pb2.BatchTranslateRequest.FromString,
                    response_serializer=protos_dot_translation__pb2.BatchTranslateResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=protos_dot_translation__pb2.HealthCheckRequest.FromString,
                    response_serializer=protos_dot_translation__pb2.HealthCheckResponse.SerializeToString,
            ),
            'IsReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsReady,
                    request_deserializer=protos_dot_translation__pb2.IsReadyRequest.FromString,
                    response_serializer=protos_dot_translation__pb2.IsReadyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'baketa.translation.v1.TranslationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('baketa.translation.v1.TranslationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranslationService(object):
    """============================================================================
    Service Definition
    ============================================================================

    / <summary>
    / Baketa翻訳サービス
    / Phase 2: gRPC通信によるPython翻訳サーバーとの連携
    / </summary>
    """

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baketa.translation.v1.TranslationService/Translate',
            protos_dot_translation__pb2.TranslateRequest.SerializeToString,
            protos_dot_translation__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranslateBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baketa.translation.v1.TranslationService/TranslateBatch',
            protos_dot_translation__pb2.BatchTranslateRequest.SerializeToString,
            protos_dot_translation__pb2.BatchTranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baketa.translation.v1.TranslationService/HealthCheck',
            protos_dot_translation__pb2.HealthCheckRequest.SerializeToString,
            protos_dot_translation__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baketa.translation.v1.TranslationService/IsReady',
            protos_dot_translation__pb2.IsReadyRequest.SerializeToString,
            protos_dot_translation__pb2.IsReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
