-- ============================================================
-- Issue #296: サーバーサイドトークン消費追跡テーブル
-- ============================================================
--
-- 目的:
-- - Patreon課金ユーザーのトークン消費をサーバーで管理
-- - ローカルファイル改ざんによる不正利用を防止
-- - 月間上限の正確な追跡
--
-- 依存関係:
-- - Issue #295: profiles.patreon_user_id が追加されていること
--
-- 実行手順:
-- 1. 先に add_patreon_user_id_to_profiles.sql を実行
-- 2. Supabase Console → SQL Editor でこのSQLを実行
-- 3. Relay Server の /api/translate でトークン消費を記録
--
-- ============================================================

-- ============================================================
-- 1. updated_at 自動更新トリガー関数（既存の場合はスキップ）
-- ============================================================
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 2. token_consumption テーブル作成
-- ============================================================
CREATE TABLE IF NOT EXISTS public.token_consumption (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ユーザー識別（profiles テーブルを参照）
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,

    -- 月単位での集計（'YYYY-MM' 形式）
    year_month TEXT NOT NULL,

    -- 消費トークン数
    tokens_used BIGINT NOT NULL DEFAULT 0,

    -- タイムスタンプ
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- 制約
    CONSTRAINT positive_tokens CHECK (tokens_used >= 0)
);

-- ============================================================
-- 3. 複合ユニークキー（1ユーザー・1月に1レコード）
-- ============================================================
ALTER TABLE public.token_consumption
DROP CONSTRAINT IF EXISTS token_consumption_user_month_key;

ALTER TABLE public.token_consumption
ADD CONSTRAINT token_consumption_user_month_key UNIQUE (user_id, year_month);

-- ============================================================
-- 4. updated_at 自動更新トリガー
-- ============================================================
DROP TRIGGER IF EXISTS set_timestamp ON public.token_consumption;

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON public.token_consumption
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

-- ============================================================
-- 5. インデックス
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_token_consumption_user_year_month
ON public.token_consumption(user_id, year_month);

CREATE INDEX IF NOT EXISTS idx_token_consumption_year_month
ON public.token_consumption(year_month);

-- ============================================================
-- 6. RLS (Row Level Security) 設定
-- ============================================================
ALTER TABLE public.token_consumption ENABLE ROW LEVEL SECURITY;

-- ユーザーは自分の消費量のみ参照可能
DROP POLICY IF EXISTS "Users can view own consumption" ON public.token_consumption;
CREATE POLICY "Users can view own consumption" ON public.token_consumption
    FOR SELECT
    USING (auth.uid() = user_id);

-- INSERT/UPDATE は service_role のみ
DROP POLICY IF EXISTS "Service role can manage consumption" ON public.token_consumption;
CREATE POLICY "Service role can manage consumption" ON public.token_consumption
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- ============================================================
-- 7. RPC関数: トークン消費を記録（UPSERT）
-- ============================================================
-- Relay Server の /api/translate 成功時に呼び出される
-- アトミックな加算でレースコンディションを防止
CREATE OR REPLACE FUNCTION record_token_consumption(
    p_user_id UUID,
    p_tokens BIGINT
)
RETURNS TABLE (
    year_month TEXT,
    tokens_used BIGINT,
    updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_year_month TEXT;
BEGIN
    -- 入力検証
    IF p_user_id IS NULL THEN
        RAISE EXCEPTION 'user_id is required';
    END IF;

    IF p_tokens <= 0 THEN
        RAISE EXCEPTION 'tokens must be positive';
    END IF;

    -- 現在の年月を取得
    v_year_month := to_char(NOW(), 'YYYY-MM');

    -- UPSERT: アトミックに加算
    INSERT INTO token_consumption (user_id, year_month, tokens_used)
    VALUES (p_user_id, v_year_month, p_tokens)
    ON CONFLICT (user_id, year_month)
    DO UPDATE SET tokens_used = token_consumption.tokens_used + p_tokens;

    -- 更新後の値を返す
    RETURN QUERY
    SELECT tc.year_month, tc.tokens_used, tc.updated_at
    FROM token_consumption tc
    WHERE tc.user_id = p_user_id AND tc.year_month = v_year_month;
END;
$$;

REVOKE ALL ON FUNCTION record_token_consumption(UUID, BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION record_token_consumption(UUID, BIGINT) TO service_role;

-- ============================================================
-- 8. RPC関数: 現在の消費量を取得（authenticated 用）
-- ============================================================
CREATE OR REPLACE FUNCTION get_my_token_consumption()
RETURNS TABLE (
    year_month TEXT,
    tokens_used BIGINT,
    updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_user_id UUID;
    v_year_month TEXT;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    v_year_month := to_char(NOW(), 'YYYY-MM');

    RETURN QUERY
    SELECT tc.year_month, tc.tokens_used, tc.updated_at
    FROM token_consumption tc
    WHERE tc.user_id = v_user_id AND tc.year_month = v_year_month;
END;
$$;

GRANT EXECUTE ON FUNCTION get_my_token_consumption() TO authenticated;

-- ============================================================
-- 9. RPC関数: Patreon ID でトークン消費を記録
-- ============================================================
-- Patreon認証のみでログインしているユーザー用
-- profiles.patreon_user_id から user_id を解決
CREATE OR REPLACE FUNCTION record_token_consumption_by_patreon(
    p_patreon_user_id TEXT,
    p_tokens BIGINT
)
RETURNS TABLE (
    year_month TEXT,
    tokens_used BIGINT,
    updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_user_id UUID;
BEGIN
    -- Patreon ID から User ID を取得
    SELECT id INTO v_user_id
    FROM profiles
    WHERE patreon_user_id = p_patreon_user_id;

    IF v_user_id IS NULL THEN
        -- Patreon連携されていない場合は記録をスキップ（エラーにしない）
        RETURN;
    END IF;

    -- 既存の関数を呼び出し
    RETURN QUERY
    SELECT * FROM record_token_consumption(v_user_id, p_tokens);
END;
$$;

REVOKE ALL ON FUNCTION record_token_consumption_by_patreon(TEXT, BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION record_token_consumption_by_patreon(TEXT, BIGINT) TO service_role;

-- ============================================================
-- 10. コメント
-- ============================================================
COMMENT ON TABLE public.token_consumption IS 'Issue #296: サーバーサイドトークン消費追跡';
COMMENT ON COLUMN public.token_consumption.user_id IS 'profiles.id への参照';
COMMENT ON COLUMN public.token_consumption.year_month IS '集計対象月（YYYY-MM形式）';
COMMENT ON COLUMN public.token_consumption.tokens_used IS '累計消費トークン数';
