name: Gemini CLI Assistant

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened, labeled]

jobs:
  gemini-assistant:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@gemini-cli')) ||
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issues' && github.event.action == 'opened')
    
    permissions:
      contents: read
      issues: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Run Gemini CLI for PR Review
        if: github.event_name == 'pull_request'
        uses: google-github-actions/run-gemini-cli@v1
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY_GITHUB_ACTIONS }}
          prompt: |
            このプルリクエストをBaketaプロジェクトの観点からレビューしてください。
            
            Baketaは：
            - Windows向けリアルタイム翻訳オーバーレイアプリケーション
            - OCR技術を使用してゲーム画面のテキストを検出・翻訳
            - クリーンアーキテクチャ（5層構造）を採用
            - C# 12/.NET 8、Avalonia UI、ReactiveUIを使用
            
            以下の観点でレビューしてください：
            1. クリーンアーキテクチャの原則への準拠
            2. C# 12の最新機能の適切な使用
            3. パフォーマンスへの影響
            4. セキュリティ上の懸念
            5. テストの必要性
            
            日本語でレビュー結果を提供してください。
            
      - name: Run Gemini CLI for Issue Triage
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: google-github-actions/run-gemini-cli@v1
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY_GITHUB_ACTIONS }}
          prompt: |
            新しいIssueを分析し、Baketaプロジェクトの適切なラベルと優先度を提案してください。
            
            Baketaの主要コンポーネント：
            - OCR (PaddleOCR)
            - 翻訳エンジン (OPUS-MT, Gemini)
            - UI (Avalonia/ReactiveUI)
            - キャプチャシステム (Windows Graphics Capture API)
            - ネイティブDLL (C++/WinRT)
            
            提案するラベル例：
            - component: ocr, translation, ui, capture, native
            - type: bug, feature, enhancement, performance
            - priority: critical, high, medium, low
            
            日本語で分析結果を提供してください。
            
      - name: Run Gemini CLI for Comments
        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '@gemini-cli')
        uses: google-github-actions/run-gemini-cli@v1
        with:
          gemini-api-key: ${{ secrets.GEMINI_API_KEY_GITHUB_ACTIONS }}
          prompt: |
            GitHub Issueまたはプルリクエストのコメントに応答してください。
            
            Baketaプロジェクトのコンテキスト：
            - Windows向けリアルタイム翻訳アプリケーション
            - クリーンアーキテクチャ、C# 12/.NET 8
            - 技術スタック: OCR、翻訳、UI、ネイティブ連携
            
            ユーザーの質問や要求に対して、技術的に正確で建設的な回答を日本語で提供してください。