# Gemini CLI Assistant - 現在無効化
# 理由: google-github-actions/run-gemini-cli@v1 アクションが存在しないため
# TODO: 将来的に適切なGemini GitHub Actionが利用可能になったら再有効化

name: Gemini CLI Assistant (Disabled)

on:
  # 一時的に無効化 - workflow_dispatchのみで手動実行可能
  workflow_dispatch:

jobs:
  gemini-assistant:
    runs-on: ubuntu-latest
    if: false  # 明示的に無効化
    
    permissions:
      contents: read
      issues: write
      pull-requests: write
      
    steps:
      - name: Placeholder
        run: echo "Gemini CLI Assistant is temporarily disabled due to missing action"

# === 将来の参考用設定（コメントアウト） ===
# 
# on:
#   issue_comment:
#     types: [created]
#   pull_request:
#     types: [opened, synchronize, reopened]
#   issues:
#     types: [opened, labeled]
#
# jobs:
#   gemini-assistant:
#     runs-on: ubuntu-latest
#     if: |
#       (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@gemini-cli')) ||
#       (github.event_name == 'pull_request') ||
#       (github.event_name == 'issues' && github.event.action == 'opened')
#     
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         
#       - name: Run Gemini CLI for PR Review
#         if: github.event_name == 'pull_request'
#         uses: google-github-actions/run-gemini-cli@v1  # <-- このアクションが存在しない
#         with:
#           gemini-api-key: ${{ secrets.GEMINI_API_KEY_GITHUB_ACTIONS }}
#           prompt: |
#             このプルリクエストをBaketaプロジェクトの観点からレビューしてください。
#             
#             Baketaは：
#             - Windows向けリアルタイム翻訳オーバーレイアプリケーション
#             - OCR技術を使用してゲーム画面のテキストを検出・翻訳
#             - クリーンアーキテクチャ（5層構造）を採用
#             - C# 12/.NET 8、Avalonia UI、ReactiveUIを使用